{"uuid": "2528df03-16a9-4a04-82ea-f15b812677f3", "counter": 12, "stdout": "\u001b[0;31mfatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Failed connection: URLError: code: 403 reason: Invalid Credential\"}\u001b[0m", "start_line": 9, "end_line": 10, "runner_ident": "989e04c0-e068-4b0d-9dbc-0b97b8a0dfd5", "event": "runner_on_failed", "pid": 17, "created": "2022-07-21T15:43:21.923063", "parent_uuid": "36761b8d-834e-cc28-146c-000000000037", "event_data": {"playbook": "1.1_palo_facts.yml", "playbook_uuid": "3c8c40f6-d330-4d14-b252-d4358c5e1deb", "play": "localhost", "play_uuid": "36761b8d-834e-cc28-146c-000000000007", "play_pattern": "localhost", "task": "Get vr info", "task_uuid": "36761b8d-834e-cc28-146c-000000000037", "task_action": "paloaltonetworks.panos.panos_virtual_router_facts", "resolved_action": "paloaltonetworks.panos.panos_virtual_router_facts", "task_args": "", "task_path": "/runner/project/roles/palo_facts/tasks/palo_vr_facts.yml:1", "role": "palo_facts", "host": "localhost", "remote_addr": "localhost", "res": {"msg": "Failed connection: URLError: code: 403 reason: Invalid Credential", "invocation": {"module_args": {"provider": {"username": "ansible_automation", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "ip_address": "10.0.0.101", "port": 443, "api_key": null, "serial_number": null}, "name": "default", "username": "admin", "port": 443, "ip_address": null, "password": null, "api_key": null, "template": null, "template_stack": null}}, "_ansible_no_log": false, "changed": false}, "start": "2022-07-21T15:43:20.182908", "end": "2022-07-21T15:43:21.922857", "duration": 1.739949, "ignore_errors": null, "event_loop": null, "uuid": "2528df03-16a9-4a04-82ea-f15b812677f3"}}